### PR TITLE
drop testing with python2.6

### PR DESCRIPTION
**Pull request by gurneyalex**
this Python version is really old.

### CODE REVIEW

**Comment by lmignon** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Comment by pedrobaeza** [comment]
But Odoo still supports it officially, so we shouldn't remove it.

**Comment by gurneyalex** [comment]
@pedrobaeza this is maintainer-tools, i.e. scripts for to help maintainers... Odoo's supported / required Python version has nothing to do with this.

**Comment by pedrobaeza** [comment]
OK then :+1:

**Pull request merged**
